export const extractedTokens = {
  pageShell: "space-y-6",
  pageHeroSection: "rounded-lg border border-slate-200 bg-white p-4 shadow-sm",
  pageBodySection: "space-y-4",
  pageTitle: "text-xl font-semibold text-slate-900",
  pageSubtitle: "text-sm text-slate-600",
  pageNoticeText: "rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900",
  pageClinicalShell: "space-y-6",
  pageClinicalHero: "rounded-lg border border-sky-200 bg-sky-50 p-4 shadow-sm",
  pageClinicalBody: "grid grid-cols-1 gap-4 xl:grid-cols-2",
  panelShell: "rounded-lg border border-slate-200 bg-white shadow-sm",
  panelTopOffset: "mt-3",
  panelBody: "p-4",
  panelSection: "space-y-4",
  panelHeader: "flex items-center justify-between gap-3",
  panelSubtleText: "text-sm text-slate-600",
  panelDivider: "border-t border-slate-200 pt-4",
  panelClinicalSection: "space-y-3",
  panelClinicalToolbar: "flex flex-wrap items-center gap-2",
  panelClinicalList: "space-y-2",
  panelClinicalListItem: "rounded-md border border-slate-200 bg-slate-50 p-3",
  compositeCard: "rounded-md border border-slate-200 bg-slate-50 p-3",
  componentBadgeBase:
    "inline-flex items-center rounded-full border px-2 py-1 text-xs font-medium",
  componentStatCard: "rounded-md border border-slate-200 bg-white p-3",
  componentFieldLabel: "text-xs font-semibold uppercase tracking-wide text-slate-600",
  componentFieldInput:
    "w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900",
  componentFieldHelp: "text-xs text-slate-500",
  componentFieldStack: "space-y-2",
  componentFormGrid: "grid grid-cols-1 gap-3 md:grid-cols-2",
  componentActionButton:
    "inline-flex items-center justify-center rounded-md bg-slate-900 px-3 py-2 text-sm font-semibold text-white",
  componentActionButtonSecondary:
    "inline-flex items-center justify-center rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-900",
  componentActionButtonDanger:
    "inline-flex items-center justify-center rounded-md border border-rose-300 bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-900",
  componentAlertBanner:
    "rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900",
  componentInputCompact:
    "w-full rounded-md border border-slate-300 bg-white px-2 py-1 text-sm text-slate-900",
  componentStatusOk: "text-sm font-medium text-emerald-700",
  componentStatusWarn: "text-sm font-medium text-amber-700",
  componentStatusError: "text-sm font-medium text-rose-700",
  metricBarTrack: "h-2 w-full rounded bg-slate-200",
  metricBarFillLow: "block h-2 rounded bg-emerald-500",
  metricBarFillMedium: "block h-2 rounded bg-amber-500",
  metricBarFillHigh: "block h-2 rounded bg-rose-500",
  metricBarWidth0: "w-0",
  metricBarWidth25: "w-1/4",
  metricBarWidth50: "w-1/2",
  metricBarWidth75: "w-3/4",
  metricBarWidth100: "w-full",
} as const;
