import { semanticTokens } from "./semanticTokens";

export const classTokens = {
  pageShell: semanticTokens.connectorPageShell,
  pageHeroSection: semanticTokens.connectorPageHeroSection,
  pageBodySection: semanticTokens.connectorPageBodySection,
  pageTitle: semanticTokens.connectorPageTitle,
  pageSubtitle: semanticTokens.connectorPageSubtitle,
  pageNoticeText: semanticTokens.connectorPageNoticeText,
  clinicalPageShell: semanticTokens.connectorClinicalPageShell,
  clinicalPageHero: semanticTokens.connectorClinicalPageHero,
  clinicalPageBody: semanticTokens.connectorClinicalPageBody,
  panelShell: semanticTokens.connectorHealthPanelContainer,
  panelTopOffset: semanticTokens.connectorHealthPanelTopOffset,
  panelBody: semanticTokens.connectorHealthPanelBody,
  panelSection: semanticTokens.connectorHealthPanelSection,
  panelHeader: semanticTokens.connectorHealthPanelHeader,
  panelSubtleText: semanticTokens.connectorHealthPanelSubtleText,
  panelDivider: semanticTokens.connectorHealthPanelDivider,
  clinicalPanelSection: semanticTokens.connectorClinicalPanelSection,
  clinicalPanelToolbar: semanticTokens.connectorClinicalPanelToolbar,
  clinicalPanelList: semanticTokens.connectorClinicalPanelList,
  clinicalPanelListItem: semanticTokens.connectorClinicalPanelListItem,
  compositeCard: semanticTokens.connectorHealthCard,
  statusBadgeBase: semanticTokens.connectorStatusBadgeBase,
  statCard: semanticTokens.connectorStatCard,
  fieldLabel: semanticTokens.connectorFieldLabel,
  fieldInput: semanticTokens.connectorFieldInput,
  fieldHelp: semanticTokens.connectorFieldHelp,
  fieldStack: semanticTokens.connectorFieldStack,
  formGrid: semanticTokens.connectorFormGrid,
  actionButton: semanticTokens.connectorActionButton,
  actionButtonSecondary: semanticTokens.connectorActionButtonSecondary,
  actionButtonDanger: semanticTokens.connectorActionButtonDanger,
  alertBanner: semanticTokens.connectorAlertBanner,
  inputCompact: semanticTokens.connectorInputCompact,
  statusOk: semanticTokens.connectorStatusOk,
  statusWarn: semanticTokens.connectorStatusWarn,
  statusError: semanticTokens.connectorStatusError,
  metricBarTrack: semanticTokens.connectorMetricBarTrack,
  metricBarFillLow: semanticTokens.connectorMetricBarFillLow,
  metricBarFillMedium: semanticTokens.connectorMetricBarFillMedium,
  metricBarFillHigh: semanticTokens.connectorMetricBarFillHigh,
  metricBarWidth0: semanticTokens.connectorMetricBarWidth0,
  metricBarWidth25: semanticTokens.connectorMetricBarWidth25,
  metricBarWidth50: semanticTokens.connectorMetricBarWidth50,
  metricBarWidth75: semanticTokens.connectorMetricBarWidth75,
  metricBarWidth100: semanticTokens.connectorMetricBarWidth100,
} as const;

export const tokenUsageExamples = [
  {
    scope: "page",
    token: "classTokens.panelShell",
    usage: "<ConnectorOpsPanel :class=\"classTokens.panelShell\" />",
  },
  {
    scope: "panel",
    token: "classTokens.panelSection",
    usage: "<section :class=\"classTokens.panelSection\">",
  },
  {
    scope: "component",
    token: "classTokens.fieldInput",
    usage: "<input :class=\"classTokens.fieldInput\" />",
  },
  {
    scope: "panel",
    token: "classTokens.formGrid",
    usage: "<form :class=\"classTokens.formGrid\">",
  },
] as const;
