apiVersion: v1
kind: Namespace
metadata:
  name: dicom-enterprise
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dicom-enterprise-default-limits
  namespace: dicom-enterprise
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 2Gi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dicom-enterprise-resource-quota
  namespace: dicom-enterprise
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 12Gi
    limits.cpu: "16"
    limits.memory: 24Gi
    pods: "30"
