apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dicom-web-runtime-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dicom-web-runtime
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dicom-workflow-runtime-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dicom-workflow-runtime
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dicom-dimse-runtime-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dicom-dimse-runtime
