apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dicom-web-runtime-state-pvc
  namespace: dicom-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dicom-workflow-runtime-state-pvc
  namespace: dicom-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dicom-dimse-runtime-state-pvc
  namespace: dicom-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
