[package]
name = "pack-seg"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dicom-core = { path = "../dicom-core" }
dicom-pixel = { path = "../dicom-pixel", optional = true }

[features]
default = ["rendering"]
pack-seg = []
rendering = ["dicom-pixel"]

[dev-dependencies]
dicom-pixel = { path = "../dicom-pixel" }
