[package]
name = "modality-pet"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []
modality-pet = []
viewer-core = ["dep:viewer-core"]

[dependencies]
dicom-core = { path = "../dicom-core" }
viewer-core = { path = "../viewer-core", optional = true }

[dev-dependencies]
sha2 = { workspace = true }
viewer-core = { path = "../viewer-core" }
