[package]
name = "viewer-wgpu"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
dicom-core = { path = "../dicom-core" }
dicom-pixel = { path = "../dicom-pixel" }
viewer-core = { path = "../viewer-core" }
wgpu = { version = "0.19", default-features = false, features = ["wgsl"] }

[dev-dependencies]
pollster = "0.3"
